name: Angular CI/CD

on:
  push:
    branches: [ main ] # Cho phép chạy khi push lên git
  workflow_dispatch: # Cho phép chạy thủ công từ GitHub UI

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Lấy source code từ repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Cài Node.js (đúng version)
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    # 3. Cài dependencies
    - name: Install dependencies
      run: npm ci

    # 4. Build Angular
    - name: Build Angular app
      run: npm run build -- --configuration production --base-href /test-ci/

    # 5. Deploy lên GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist/test-ci-angular # Thay bằng tên folder build Angular
