name: Angular CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Lấy source code từ repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Cài Node.js (đúng version)
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    # 3. Cài dependencies
    - name: Install dependencies
      run: npm ci

    # 4. Build Angular
    - name: Build Angular app
      run: npm run build --if-present

    # 5. (Tùy chọn) Chạy unit tests
    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless
